[package]
name = "rustKart"
version = "0.1.0"
edition = "2021"

[dependencies]
chinchilib = "0.3"
env_logger = "0.11"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "rustkart"
path = "src/main.rs"
